Add design spec
zingolabs/zingo-proxy pull request #104
Opened 2024-11-15 02:57 UTC by idky137

Adds design docs and specifications to Zaino.

- Closes #53

2024-11-15 20:36 UTC, idky137 commented
Only docs have changed, best to look at the branch while reviewing to see correct views.

2024-11-15 21:55 UTC, pacu requested changes

2024-11-15 21:55 UTC, pacu commented on Cargo.toml
> +# TODO: Move to crate level.
In my experience, TODOs that don't have an associated issues don't get done. 

Also this is a good-first-issue kind of thing.  Which is good for newcomers. Take that opportunity!

2024-11-15 21:55 UTC, pacu commented on README.md
> +Zaino is a Rust-implemented indexer for Zcash.
is it rust more important than the actual goal of the project? 
```suggestion
Zaino is an indexer for the Zcash blockchain implemented in Rust.
```

2024-11-15 21:55 UTC, pacu commented on README.md
> +Zaino provides all necessary functionality for "standalone" (formerly "light") clients / wallets, "integrated" (formerly "full") clients / wallets, and block explorers to access both the finalized ch
Renaming existing terminology opaques the goal of the README which is introducing Zaino to a newcomer. Leave this for further entries, like a glossary.
```suggestion
Zaino provides all necessary functionality for "light" clients (wallets and other applications that don't rely on the complete history of blockchain) and "full" clients / wallets and block explorers providing access both the finalized chain and the non-finalized best chain and mempool held by either a Zebra or Zcashd full validator.
```

Also "standalone" and "integrated" sound kind of confusing to me. A standalone client contradicts the term "light" client given that the nature of a light-client can't operate on its own. A full-node wallet on the other hand can be a "standalone" solution because it sustains itself.

2024-11-15 21:55 UTC, pacu commented on README.md
> +With the ongoing Zcashd deprecation project, there is a push to transition to a modern, Rust-based software stack for the Zcash ecosystem. By implementing Zaino in Rust, we aim to modernize the codeb
```suggestion
With the ongoing Zcashd deprecation project, there is a push to transition to a modern, Rust-based software stack for the Zcash ecosystem. By implementing Zaino in Rust, we aim to modernize the codebase, enhance performance and improve overall security. This work will build on the foundations laid down by [Librustzcash](https://github.com/zcash/librustzcash) and [Zebra](https://github.com/ZcashFoundation/zebra), helping to ensure that the Zcash infrastructure remains robust and maintainable for the future.
```

2024-11-15 21:55 UTC, pacu commented on README.md
> +Due to current potential data leaks / security weaknesses highlighted in [revised-nym-for-zcash-network-level-privacy](https://forum.zcashcommunity.com/t/revised-nym-for-zcash-network-level-privacy/4
I dislike remarking obviousness of a fact because it undermines those who might not have considered it unnecessarily. 

```suggestion
Due to current potential data leaks / security weaknesses highlighted in [revised-nym-for-zcash-network-level-privacy](https://forum.zcashcommunity.com/t/revised-nym-for-zcash-network-level-privacy/46688) and [wallet-threat-model](https://zcash.readthedocs.io/en/master/rtd_pages/wallet_threat_model.html), there is a need to use anonymous transport protocols (such as Nym or Tor) to obfuscate clients' identities from Zcash's indexing servers ([Lightwalletd](https://github.com/zcash/lightwalletd), [Zcashd](https://github.com/zcash/zcash), Zaino). As Nym has chosen Rust as their primary SDK ([Nym-SDK](https://github.com/nymtech/nym)), and Tor is currently implementing Rust support ([Arti](https://gitlab.torproject.org/tpo/core/arti)), Rust is a straight-forward and well-suited choice for this software.
```

2024-11-15 21:55 UTC, pacu commented on README.md
> +Separation of validation and indexing functionality serves several purposes. Primarily, removing indexing functionality from the Validator (Zebra) will lead to a smaller and more maintainable codebas
Split long sentences into small and more concise ones. Prioritize Zaino's goals over context and history.
```suggestion
Separation of validation and indexing functionality serves several purposes. First, by removing indexing functionality from the Validator (Zebra) will lead to a smaller and more maintainable codebase. Second, by moving all indexing functionality away from Zebra into Zaino will unify this paradigm and simplify Zcash's security model. Separating this concerns (consensus node and blockchain indexing) serves to create a clear trust boundary between the Indexer and Validator allowing the Indexer to take on this responsibility. Historically, this had been the case for "light" clients/wallets using [Lightwalletd](https://github.com/zcash/lightwalletd) as opposed to "full-node" client/wallets and block explorers that were directly served by the [Zcashd full node](https://github.com/zcash/zcash). 
```

2024-11-15 21:55 UTC, pacu commented on README.md
> +Our primary goal with Zaino is to serve all non-miner clients, such as wallets and block explorers, in a manner that prioritizes security and privacy while also ensuring the time efficiency critical
```suggestion
Our primary goal with Zaino is to serve all non-miner clients -such as wallets and block explorers- in a manner that prioritizes security and privacy while also ensuring the time efficiency critical to a stable currency. We are committed to ensuring that these clients can access all necessary blockchain data and services without exposing sensitive information or being vulnerable to attacks. By implementing robust security measures and privacy protections, Zaino will enable users to interact with the Zcash network confidently and securely.
```

2024-11-15 21:55 UTC, pacu commented on README.md
> +To facilitate a smooth transition for existing users and developers, Zaino is designed, where possible, to maintain full backward compatibility with Lightwalletd and Zcashd. This means that applicati
"where possible" means best effort on possibility. This contradicts "full" backward compatibility. I removed the term "full".

```suggestion
To facilitate a smooth transition for existing users and developers, Zaino is designed (where possible) to maintain backward compatibility with Lightwalletd and Zcashd. This means that applications and services currently relying on these platforms can switch to Zaino with minimal adjustments. By providing compatible APIs and interfaces, we aim to reduce friction in adoption and ensure that the broader Zcash ecosystem can benefit from Zaino's enhancements without significant rewrites or learning curves.
```

2024-11-15 21:55 UTC, pacu commented on README.md
> +Zaino will extend the functionality of Zebra's ReadStateService, using a Hyper wrapper, to offer remote read access to the chain state data held by Zebra. This will primarily be designed as a remote
I don't understand what developers can and can't use.

2024-11-16 02:41 UTC, Oscar-Pepper requested changes
spec looks great! I think @pacu did a great job of proof-reading the README.md I agree with his comments. only found a small spelling mistake. Great work!

2024-11-16 02:41 UTC, Oscar-Pepper commented on docs/internal_spec.md
> +* We plan to eventually rely on `LibRustZcash`'s versions but hold our our here for development purposes.
```suggestion
* We plan to eventually rely on `LibRustZcash`'s versions but hold our own here for development purposes.
```

2024-11-18 13:17 UTC, idky137 commented on Cargo.toml
> +# TODO: Move to crate level.
Added in [968fe5e].

2024-11-18 13:17 UTC, idky137 commented on README.md
> +Zaino is a Rust-implemented indexer for Zcash.
Added in [968fe5e].

2024-11-18 13:18 UTC, idky137 commented on README.md
> +Zaino provides all necessary functionality for "standalone" (formerly "light") clients / wallets, "integrated" (formerly "full") clients / wallets, and block explorers to access both the finalized ch
Added in [968fe5e].

2024-11-18 13:18 UTC, idky137 commented on README.md
> +With the ongoing Zcashd deprecation project, there is a push to transition to a modern, Rust-based software stack for the Zcash ecosystem. By implementing Zaino in Rust, we aim to modernize the codeb
Added in [968fe5e].

2024-11-18 13:18 UTC, idky137 commented on README.md
> +Due to current potential data leaks / security weaknesses highlighted in [revised-nym-for-zcash-network-level-privacy](https://forum.zcashcommunity.com/t/revised-nym-for-zcash-network-level-privacy/4
Added in [968fe5e].

2024-11-18 13:18 UTC, idky137 commented on README.md
> +Our primary goal with Zaino is to serve all non-miner clients, such as wallets and block explorers, in a manner that prioritizes security and privacy while also ensuring the time efficiency critical
Added in [968fe5e].

2024-11-18 13:19 UTC, idky137 commented on README.md
> +To facilitate a smooth transition for existing users and developers, Zaino is designed, where possible, to maintain full backward compatibility with Lightwalletd and Zcashd. This means that applicati
Added in [968fe5e].

2024-11-18 13:19 UTC, idky137 commented on README.md
> +Zaino will extend the functionality of Zebra's ReadStateService, using a Hyper wrapper, to offer remote read access to the chain state data held by Zebra. This will primarily be designed as a remote
Updated in [968fe5e], I think it is now more understandable.

2024-11-18 13:19 UTC, idky137 commented on docs/internal_spec.md
> +* We plan to eventually rely on `LibRustZcash`'s versions but hold our our here for development purposes.
Added in [968fe5e].

2024-11-18 13:20 UTC, idky137 commented on README.md
> +Separation of validation and indexing functionality serves several purposes. Primarily, removing indexing functionality from the Validator (Zebra) will lead to a smaller and more maintainable codebas
Added in [968fe5e].

2024-11-19 01:52 UTC, Oscar-Pepper approved these changes
wonderful

2024-11-19 01:53 UTC, merged