Allow connecting to Zebrad on any hostname
zingolabs/zingo-proxy pull request #115
Opened 2024-11-20 03:11 UTC by emersonian

This patch allows for Zaino to connect to a Zebrad that is not running on localhost.

This is my first-ever Rust pull request so bear with me! I am unsure how to run the tests, am happy to fix anything that broke.

Thank you for your great work on Zaino!

2024-11-20 10:25 UTC, daira commented
I am opposed to merging this. We need to establish a strong security norm and expectation that the connection between Zaino and Zebrad is within a trust boundary. That is, we must be able to make the design assumption that Zaino can trust the Zebrad it is connected to, because it *necessarily* is run by the same party.

2024-11-20 17:01 UTC, emersonian commented
How can this be tested in a staging environment without the ability to connect to other hosts? I'm all for including warnings in the documentation with your concerns, but restricting to only allowing zebra to run on localhost is excessive and slows down integration testing across stakeholders.

Use case: Zec.rocks has around ten zebra instances synced and running around the world. I took two out of our public load balancers (one mainnet, one testnet) and am pointing Zaino at them for integration testing, all communicating within their clusters' internal network. There is no security risk in this case, internal communications are encrypted by the Container Network Interface (CNI).

Restricting to localhost slows down the development of Docker Compose and Kubernetes configs for Zaino. Sure, add warnings, but don't force everyone to run Zebra on localhost.

2024-11-21 15:31 UTC, idky137 commented
Could we query Zebra's `enable_cookie_auth` setting using the RPC server? We could then enforce `cookie_auth=true` when connecting to Zebra remotely? We could also add something similar for Zcashd using the user and password fields in its RPC server. Im not sure how disruptive this would be Zec.rocks though?

2024-11-21 15:33 UTC, idky137 commented
Code looks good though!

2024-11-26 19:23 UTC, idky137 commented
Hey sorry I haven't got back regarding this. 

I want to make sure everyone is happy with the decision we make regarding how we open up Zaino for remote use before merging anything into dev. 

We do have work planned for connecting to zebra remotely in Milestone 3 of our current grant (https://github.com/zingolabs/zaino/issues/58) but that is a few months away and will not be focusing on the RPC backend in Zaino.

I want to make sure Zaino can be used how the community wants though so think it would be good to work out a solution for the RPC backend separate to that.

2024-11-27 22:09 UTC, emersonian commented
I suggest that we start by matching the security modeling of lightwalletd rather than further restricting it. Lightwalletd allows connection to node RPCs running on any configurable host, today. If we want to improve upon that level of security, let's decide in a separate discussion.

Zaino must work in containers/Docker. Listening only on localhost is a no-starter for supporting containers.

2024-12-30 14:39 UTC, idky137 commented
I will raise this at one of the next arborist calls, originally I had planned to open up zaino for remote use around this time and agree we are not adding any new security weaknesses but want to check.. 

We do have time put aside in milestone 3 for enabling "safe" remote access to zebra but I would like to make it possible for you to start testing zaino before then. 

Maybe we can merge this functionality under an "unstable" feature flag during development.

2025-01-10 18:50 UTC, zancas commented
I have heard a proposal to enable "testing_very_insecure" as a conditionally compiled feature.   That seems sensible to me.

I don't think a few months of testing until MileStone 3 is complete is too much time in test mode.

2025-01-10 19:54 UTC, idky137 commented
If we are happy with this I will have another look at this pr once #153 lands, there have been some structural changes and I think there will be a couple other places that this code will need to propaget to. I will also look at adding the feature flag.

2025-01-27 22:53 UTC, emersonian commented
Flagging this as a blocker, zec.rocks cannot run zaino until it works in cloud-native environments (Kubernetes or Docker).

This is the standard [across other projects](https://zebra.zfnd.org/user/docker.html) that zaino needs to meet:

cd zaino
docker compose up
# (Spins up zaino and zebra, works locally once synced)

2025-01-30 22:50 UTC, pacu requested changes
Setting aside discussions on  whether connecting to non-local nodes should be allowed these changes could introduce some improvements

2025-01-30 22:50 UTC, pacu commented on zainod/src/config.rs
> +    println!("Loading config: {:?}", file_path);
shall this be a call so some logger?

2025-01-30 22:50 UTC, pacu commented on zainod/src/config.rs
> +        eprintln!("File does not exist: {:?}", file_path);
Is this a debug call or some problem?

2025-01-30 22:50 UTC, pacu commented on zainod/src/config.rs
>  pub fn load_config(file_path: &std::path::PathBuf) -> IndexerConfig {
this should be a fallible function that returns some error

2025-01-30 22:50 UTC, pacu commented on zainod/src/config.rs
> +        Err(e) => eprintln!("Error reading file: {}", e),
Return Error

2025-02-04 14:04 UTC, idky137 commented
Hey, thanks for the review! Due to quite a lot of changes that have happened in zaino since this PR was opened this work will now be completed in #180

2025-02-07 18:20 UTC, pacu commented
according to @emersonian there was some agreement on how to settle this. What are the next steps for this PR? Closing, further modifications?

2025-02-07 18:34 UTC, arya2 commented
SSH port forwarding may be a good alternative to this change, though adding a `testing-very-insecure` rust compilation config flag seems okay too.

2025-02-14 20:04 UTC, closed without merging