Cratify workspace
zingolabs/zingo-proxy pull request #7
Opened 2024-04-17 17:26 UTC by idky137

Cratifying zingo-proxy to improve usability and separate functionality.

2024-04-23 14:59 UTC, idky137 commented
May be better to use the underlying feature branch for review as almost everything has moved so looking at changes may be confusing. The only new code is in zingo-proxyd::grpc, this is a mirror of zingolib::zingo_netutils and has been moved here to reduce dependencies.

2024-04-23 15:00 UTC, idky137 commented
CI currently does not work as lightwalletd/zebrad need to be launched manually, meaning tests cannot be run in CI. This will be fixed in a separate pr.

2024-04-25 16:25 UTC, AloeareV approved these changes

2024-04-25 16:29 UTC, AloeareV requested changes
I'd like to keep the single source of zingo-netutils. Other than that, the cratifaction is great!

2024-04-26 03:08 UTC, AloeareV approved these changes

2024-04-29 16:39 UTC, merged