Bump deps
zingolabs/zingo-proxy pull request #76
Opened 2024-10-08 19:47 UTC by idky137

This PR will update the zingolib, librustzcash and rustc versions used by Zaino.

- This will complete the majority of work required for #48. The remaining changes for ZIP320 will be small and can be made once ZIP230 stabalises in zingolib.

2024-10-08 19:48 UTC, idky137 commented
built atop of #74 and #75

2024-10-09 17:42 UTC, idky137 commented
monitor_unverified_mempool test fails due to changes in mempool transaction height. this will be fixed in a separate PR.

2024-10-16 13:11 UTC, Oscar-Pepper requested changes
i dont think the mempool will work correctly if we clone the LC. see my comments

2024-10-16 13:11 UTC, Oscar-Pepper commented on zaino-testutils/src/lib.rs
> +            .map(|tx_ids| tx_ids.into_iter().next().unwrap().to_string())
why not just import and use `from_inputs::quick_send` directly? then in the tests you can call `.first()` if you want to ignore the multiple txids returned

2024-10-16 13:11 UTC, Oscar-Pepper commented on zaino-testutils/src/lib.rs
> +        zingolib::lightclient::LightClient::start_mempool_monitor(zingo_client_loaded.clone());
hmmm.. im not sure this will work as the mempool monitor is attached to a clone of the lightclient that wants to sync from mempool. I think we want to put the lightclient in an Arc in the code where we want to start the mempool and then call the zingolib version of `start_mempool_monitor` directly. then any other time the lightclient is called in the code you can use the lightclient in the arc but still pass it to mempool

2024-10-16 13:11 UTC, Oscar-Pepper commented on zaino-testutils/src/lib.rs
> +        zingolib::lightclient::LightClient::start_mempool_monitor(zingo_client_loaded.clone());
this is my blocking comment btw, i think this needs to change

2024-10-17 16:13 UTC, Oscar-Pepper approved these changes
on the grounds that the mempool is working and these changes are best made on top of a later PR, i am merging this as is.

2024-10-17 16:13 UTC, merged