Implement Get block range nullifiers
zingolabs/zingo-proxy pull request #86
Opened 2024-10-30 11:54 UTC by idky137

Implements the get_block_range_nullifers gRPC service.

Currently there are no tests for this in Zaino, these will be added when the last PRs for [https://github.com/zingolabs/zcash-local-net] land and we can integrate that repo into Zaino-testutils. There is a test in [https://github.com/zingolabs/zcash-local-net] that tests this function "integrations::get_block_range_nullifiers".

- Work towards https://github.com/zingolabs/zaino/issues/52

- Built atop https://github.com/zingolabs/zaino/pull/82, https://github.com/zingolabs/zaino/pull/84 and #85

2024-10-31 03:43 UTC, Oscar-Pepper requested changes
im concerned an unchecked cast from u64 to u32 could cause undefined overflow behaviour etc.

2024-10-31 03:43 UTC, Oscar-Pepper commented on zaino-serve/src/rpc/service.rs
> +                .map(|s| s.height as u32)
`as` performs an unchecked cast. consider using from / into here

2024-10-31 18:38 UTC, idky137 commented on zaino-serve/src/rpc/service.rs
> +                .map(|s| s.height as u32)
Added change in [fc22fc2]. Also fixed error messages.

2024-11-01 16:20 UTC, Oscar-Pepper approved these changes

2024-11-01 16:21 UTC, merged