Fix get block range
zingolabs/zingo-proxy pull request #87
Opened 2024-10-30 17:15 UTC by idky137

Fixes the order that compact blocks are returned in by the get_block_range and get_block_range_nullifiers RPCs. Before they were always returned in descending order, now they are returned in the order that they are requested in (start -> end).

- There is a test in [https://github.com/zingolabs/zcash-local-net] that tests this function "integrations::get_block_range_nullifiers".

- Work towards https://github.com/zingolabs/zaino/issues/52

- Built atop https://github.com/zingolabs/zaino/pull/82, https://github.com/zingolabs/zaino/pull/84, https://github.com/zingolabs/zaino/pull/85 and #86

2024-10-31 03:53 UTC, Oscar-Pepper requested changes

2024-10-31 03:53 UTC, Oscar-Pepper commented on zaino-serve/src/rpc/service.rs
> +            };
im not sure i like the fact that this doesn't error when the start is higher than the end ... this would error if it was a true `Range` rust struct so im not sure why this is supported. is this how lwd works??

2024-10-31 03:53 UTC, Oscar-Pepper commented on zaino-serve/src/rpc/service.rs
> +            };
i will add this test to zcash-local-net to check

2024-10-31 03:53 UTC, Oscar-Pepper commented on zaino-serve/src/rpc/service.rs
> +                .map(|s| s.height as u32)
can we use from / into here for a checked cast from u64 to u32?

2024-10-31 18:44 UTC, idky137 commented on zaino-serve/src/rpc/service.rs
> +            };
This is actually the correct behaviour. When the start is higher than the end the blocks are returned in descending order. This is how zingolib currently asks for blocks.

2024-10-31 18:45 UTC, idky137 commented on zaino-serve/src/rpc/service.rs
> +            };
Lines 237:242 reverse the block order fetched if rev_order is true.

2024-11-01 17:14 UTC, idky137 commented on zaino-serve/src/rpc/service.rs
> +                .map(|s| s.height as u32)
This was updated in a separate PR and added here in [2da2481]

2024-11-02 05:43 UTC, Oscar-Pepper commented on zaino-serve/src/rpc/service.rs
> +            };
oh ok i will merge!

2024-11-02 05:44 UTC, Oscar-Pepper approved these changes

2024-11-02 05:45 UTC, merged