integrate zcash local net test fixtures into zaino tests
zingolabs/zingo-proxy pull request #88
Opened 2024-11-02 07:31 UTC by Oscar-Pepper

2024-11-05 15:49 UTC, idky137 commented
Work towards https://github.com/zingolabs/zaino/issues/51

2024-11-07 15:02 UTC, idky137 requested changes
Code all looks good. Im getting errors running tests though. Is there anything I need to do apart from build release? Could you add to the Testing section of the readme?

2024-11-07 15:03 UTC, idky137 requested changes
Code all looks good. Im getting errors running tests though. Is there anything I need to do apart from build release? Could you add to the Testing section of the readme?

2024-11-09 03:14 UTC, Oscar-Pepper commented
> Code all looks good. Im getting errors running tests though. Is there anything I need to do apart from build release? Could you add to the Testing section of the readme?

ok i have added to the readme. I am ignoring mempool tests until https://github.com/zingolabs/zcash-local-net/pull/19 merges

2024-11-11 06:48 UTC, Oscar-Pepper commented
i have unignored mempool tests and pointed at my branch for now. we can clean this up later when zcash_local_net is up to date

2024-11-11 12:45 UTC, idky137 requested changes

2024-11-11 12:45 UTC, idky137 commented on README.md
> +3) Generate the chain cache `cargo nextest run generate_zcashd_large_chain_cach --run-ignored ignored-only --features test_fixtures`
This is returning an error:

$ cargo nextest run generate_zcashd_large_chain_cach --run-ignored ignored-only --features test_fixtures
error: none of the selected packages contains these features: test_fixtures

Does this feature need to be added to zaino?

Edit: line 63 should be:

3) Generate the chain cache `cargo nextest run generate_zcashd_chain_cach --run-ignored ignored-only --features test_fixtures`

2024-11-11 13:32 UTC, idky137 commented on README.md
> +3) Generate the chain cache `cargo nextest run generate_zcashd_large_chain_cach --run-ignored ignored-only --features test_fixtures`
fixed in 65d5d6f.

2024-11-11 13:33 UTC, idky137 approved these changes

2024-11-11 13:33 UTC, merged